apiVersion: v1
kind: Service
metadata:
  name: k8s-owl-fe
  labels:
    name: k8s-owl-fe
spec:
  ports:
    - port: 8001
      targetPort: http-port
      protocol: TCP
      nodePort: 30080
  externalIPs:
    - 192.168.120.135
  selector:
    app: k8s-fe
  type: NodePort
