apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fe
  labels:
    app: k8s-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-fe
  template:
    metadata:
      labels:
        app: k8s-fe
    spec:
      containers:
        - name: k8s-fe
          image: service-owl:5000/k8s-owl-fe:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
